### ISSUE TITLE
`cache.set(key, value, None)` does not default to infinite/no expiry

### ISSUE THREAD

**Issue by dan-lumafield** [xncbf/django-dynamodb-cache#18]
Hello! This is an awesome project -- really appreciate it!

I ported some code which had been using the django in-memory cache where a call similar to:
```
cache.set(key, value, None)
```
would result in an infinite cache expiration.

In `django-dynamodb-cache` it seems like this results in the cache picking up the default timeout value, which is either set in the `settings.py` or is 120 seconds. 

I looked a bit through the code and it also seems like a concept of a non-expiring cache key isn't fully supported at the moment.

It would be great for this extension to support non-expiring caches, and if `cache.set(key, value, None)` could result in a non-expiring cache key.

Thanks!

**Comment by xncbf** [comment]
Thanks for reporting the issue! I will provide a patch as soon as possible.

**Comment by dan-lumafield** [comment]
Thank you!
